version: '2.3'

x-volumes:
  &default-volumes
    # Define all volumes you would like to have real-time mounted into the docker containers
    volumes:
      - .:/app:delegated ### Local overrides to mount host filesystem. Automatically removed in CI and PROD.

services:

  cli:
    build:
      context: .
      dockerfile: Dockerfile
    << : *default-volumes # loads the defined volumes from the top
